Testing Logic and Components
balerum03/React-calculator pull request #8
Opened 2021-05-20 18:09 UTC by balerum03

Added test:
- Unit testing for Logic.
- Snapshot testing for React components.

2021-05-21 05:08 UTC, uche-inyama requested changes
## Changes Required

### Hi balerum03 :slightly_smiling_face: 

Good job, you are almost through with the tests. It is required that all functions in the calculate.js file are covered with unit tests, but tests for **%** and **+/-** were not covered.

#### Make these updates then request for another code review.

### Happy coding :man_technologist: 

#### ``` Uchechukwu Henry Inyama ```

2021-05-21 22:49 UTC, Forison requested changes
## Status::Changes Required ❌

# 👋 @balerum03 

#### Good job on adding test to cover `%` and `+/-` as requested earlier, however there are a few issue we have to address to the project approved😇.

* [ ] Kindly check my comments below👇.

#### That is it, kindly make the changes and submit a re-review💪

#### Happy coding👨‍💻

Addo Forison

2021-05-21 22:49 UTC, Forison commented on .env
> +SKIP_PREFLIGHT_CHECK=true
* [ ] Never commit .env file to repo, add the path to your `gitignore` so they don't get commit to the remove branch

2021-05-21 22:49 UTC, Forison commented on src/logic/__test__/calculate.test.js
> +describe('User can user %', () => {
Let us improve the description here, I bet you wanted to say `User can use %`. Let us rectify this.

2021-05-21 22:49 UTC, Forison commented on src/logic/__test__/calculate.test.js
> +  test('user changes the from negative to positive', () => {
* [ ] Let us add a scenario where ie user enters `2` `+` `4` and then selects `+/-`

2021-05-21 22:52 UTC, Forison commented on src/logic/__test__/calculate.test.js
> +});
* [ ] Let us add a scenario where ie user enters `2` `+` `4` and then selects `%`

2021-05-22 13:32 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-05-23 05:20 UTC, merged